# Generated by Django 2.2.5 on 2019-09-12 06:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=200, unique=True)),
                ('author', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('borrowed_by_who', models.CharField(max_length=200)),
                ('borrowed_till', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
