# Generated by Django 2.2.5 on 2019-09-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20190916_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='borrowed_till',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
